// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Create(arg1, arg2, arg3) {
  return window['go']['main']['App']['Create'](arg1, arg2, arg3);
}

export function CreateOverwrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateOverwrite'](arg1, arg2, arg3);
}

export function DeleteAssembly(arg1, arg2) {
  return window['go']['main']['App']['DeleteAssembly'](arg1, arg2);
}

export function DeleteComponent(arg1) {
  return window['go']['main']['App']['DeleteComponent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Help() {
  return window['go']['main']['App']['Help']();
}

export function InputAssembly(arg1, arg2) {
  return window['go']['main']['App']['InputAssembly'](arg1, arg2);
}

export function InputComponent(arg1, arg2) {
  return window['go']['main']['App']['InputComponent'](arg1, arg2);
}

export function IsOpen() {
  return window['go']['main']['App']['IsOpen']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function PrintAll() {
  return window['go']['main']['App']['PrintAll']();
}

export function PrintComponent(arg1) {
  return window['go']['main']['App']['PrintComponent'](arg1);
}

export function RestoreAll() {
  return window['go']['main']['App']['RestoreAll']();
}

export function RestoreComponent(arg1) {
  return window['go']['main']['App']['RestoreComponent'](arg1);
}

export function Truncate() {
  return window['go']['main']['App']['Truncate']();
}
