// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Create(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CreateOverwrite(arg1:string,arg2:number,arg3:string):Promise<void>;

export function DeleteAssembly(arg1:string,arg2:string):Promise<void>;

export function DeleteComponent(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Help():Promise<string>;

export function InputAssembly(arg1:string,arg2:string):Promise<void>;

export function InputComponent(arg1:string,arg2:string):Promise<void>;

export function IsOpen():Promise<boolean>;

export function Open(arg1:string):Promise<void>;

export function PrintAll():Promise<string>;

export function PrintComponent(arg1:string):Promise<string>;

export function RestoreAll():Promise<void>;

export function RestoreComponent(arg1:string):Promise<void>;

export function Truncate():Promise<void>;
